### ISSUE TITLE
unknown "uv"

### ISSUE THREAD

**Issue by davidosomething** [tzachar/highlight-undo.nvim#1]
https://github.com/tzachar/highlight-undo.nvim/blob/77d28cd31d509f8669a922739a76d47aff7d0de0/lua/highlight-undo.lua#L11

should be vim.loop.new_timer?

**Comment by tzachar** [comment]
`vim.loop` has been deprecated.
Which nvim version are you using?

**Comment by chrisgrieser** [comment]
I have the same problem.

```
macOS 13.4 (M1)
neovim 0.9.1 (homebrew)
Neovide 0.10.4 (homebrew)
```

**Comment by nyngwang** [comment]
I think ~~`vim.uv`~~ is deprecated in nvim v0.10? **update**: lol, I meant `vim.loop`, was sleepy when typing.

**Comment by tzachar** [comment]
Its the other way around, as far as I can tell...
