### ISSUE TITLE
FR: Option disable messages like `1 less line` etc.

### ISSUE THREAD

**Issue by chrisgrieser** [tzachar/highlight-undo.nvim#13]
Without this plugin, simply using `silent` would work. With this plugin, I am not totally sure how to make nvim ignore all those messages that popup with *every single* undo/redo.

**Comment by tzachar** [comment]
you can achieve this through the config:
```lua
require('highlight-undo').setup({
    hlgroup = 'HighlightUndo',
    duration = 300,
    keymaps = {
      {'n', 'u', 'silent undo', {silent=true}},
      {'n', '<C-r>', 'silent redo', {silent=true}},
    }
})
```

**Comment by chrisgrieser** [comment]
ah, I see, thanks!
