### ISSUE TITLE
Respect count

### ISSUE THREAD

**Issue by sassanh** [tzachar/highlight-undo.nvim#15]
When I press `8u` it doesn't undo 8 times, I guess it is ignoring `<count>`.

**Comment by tzachar** [comment]
I think that due to the way the plugin works (by hijacking the 'u' mapping), this would be impossible.

**Comment by sassanh** [comment]
I tried to implement it here: https://github.com/tzachar/highlight-undo.nvim/pull/16
Please check if it is good enough to merge.
