### ISSUE TITLE
Add option to ignore specific filetypes

### ISSUE THREAD

**Issue by mambusskruj** [tzachar/highlight-undo.nvim#17]
For example, https://github.com/simrat39/symbols-outline.nvim (filetype=Outline) constantly update its buffer with cursor movements. Nice to have option to disable highlight for specific filetypes.

**Comment by tzachar** [comment]
I would gladly accept such a PR :wink:

**Comment by mambusskruj** [comment]
Alright, I could try

**Comment by jemag** [comment]
@tzachar I see this has been closed as completed but I cannot find any related commit or documentation about this feature. Could you clarify how to ignore specific filetypes?

**Comment by tzachar** [comment]
Completed here did not meant implemented :-)
I asked for a PR, and will still accept one...

**Comment by mambusskruj** [comment]
yeah, my bad, excuse me. still plan to look tho.
