### ISSUE TITLE
Link to default highlight group instead of defining colors in the plugin

### ISSUE THREAD

**Issue by gbprod** [tzachar/highlight-undo.nvim#20]
Hi and thanks for this plugin :)

IMHO, to improve colorscheme compatibility, colors should not be defined in the plugin, it rather lin to an existing default highlight group (here, `Search` would be great in my opinion).

I know it will breaks BC, but maybe we could add a temporary notification during transition ? Let me know if you're ok, I can open a PR.

Thanks :)

**Comment by tzachar** [comment]
Well, you can set your own hl group on setup.
And most colorschemes today target specific plugins' hl groups.

**Comment by gbprod** [comment]
I understand your point and it's up to you to choose how you want to manage your plugin :wink:  (I've already [update my colorscheme to handle your plugin](https://github.com/gbprod/nord.nvim/pull/45)). 
Anyway, using a link, allows your plugin to be compatible with most of colorscheme without any changes, and it's in my opinion a good practice and very convenient.

Fyi, lots of popular plugins (like [telescope](https://github.com/nvim-telescope/telescope.nvim/blob/74ce793a60759e3db0d265174f137fb627430355/plugin/telescope.lua#L13-L90), [Lazy](https://github.com/nvim-telescope/telescope.nvim/blob/74ce793a60759e3db0d265174f137fb627430355/plugin/telescope.lua#L13-L90), [which-key.nvim](https://github.com/folke/which-key.nvim/blob/7ccf476ebe0445a741b64e36c78a682c1c6118b7/lua/which-key/colors.lua#L15), [yanky](https://github.com/gbprod/yanky.nvim/blob/cc3fc03c780a14f189290edcf1c47dc1306626d4/lua/yanky/highlight.lua#L9) or [lsp-config](https://github.com/neovim/nvim-lspconfig/blob/60e7d993849cb8161cb1ffbedbb47a0c947e76be/plugin/lspconfig.lua#L58)) uses links when it's possible :)

**Comment by tzachar** [comment]
Well, I don't really have an opinion on this.
My only concern is breaking BC.

If you can address that, I will consider a PR. btw, a warning (like you suggested in the OP) is not enough in my opinion.
