### ISSUE TITLE
Create a `HighlightRedo` hlgroup to simplify colorscheme support

### ISSUE THREAD

**Issue by igorlfs** [tzachar/highlight-undo.nvim#21]
Hello, there!

Nice plugin! I was wondering if it would be possible to create a new highlight group, exclusively for the redo action. It could be linked to `HighlightUndo` by default. The idea is that colorschemes could set each highlight group to different colors and no config parameters would be necessary for users.

**Comment by tzachar** [comment]
Sure.
I'll accept such a PR happily :)

**Comment by igorlfs** [comment]
Hey, thanks for the quick reply! PR opened!
