### ISSUE TITLE
Issue configuring the plugin

### ISSUE THREAD

**Issue by pidgeon777** [tzachar/highlight-undo.nvim#24]
My issue pertains to the configuration of the `highlight-undo.nvim` plugin in Neovim. The plugin is designed to provide visual feedback when undo and redo operations are performed. However, despite the correct execution of undo and redo operations, the expected highlighting is not being displayed.

The current configuration of the plugin is as follows:

```lua
return {
  {
    "tzachar/highlight-undo.nvim",
    opts = function(_, opts)
      local def_opts = {
        duration = 300,
        undo = {
          hlgroup = "HighlightUndo",
          mode = "n",
          lhs = "u",
          map = "undo",
          opts = {},
        },
        redo = {
          hlgroup = "HighlightRedo",
          mode = "n",
          lhs = "<C-r>",
          map = "redo",
          opts = {},
        },
        highlight_for_count = true,
      }

      local my_opts = def_opts
      my_opts.undo.lhs = "<C-M-Left>"
      my_opts.redo.lhs = "<C-M-Right>"

      opts = vim.tbl_deep_extend("force", opts or {}, my_opts)

      return opts
    end,
  },
}
```

The key mappings for undo and redo operations are set to `<C-M-Left>` and `<C-M-Right>` respectively, as shown in the following code:

```lua
-- Undo history
vim.api.nvim_set_keymap("n", "<C-M-Left>", "u", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-M-Right>", "<C-r>", { noremap = true, silent = true })
```

Despite this configuration, the expected highlighting is not being displayed when the undo and redo operations are triggered using the Ctrl+Alt+Left/Right keys. The operations themselves are executed correctly, but the visual feedback provided by the `highlight-undo.nvim` plugin is not being shown.

**Comment by tzachar** [comment]
You need to specify you binding for undo and redo only in the configuration and not use `vim.api.nvim_set_keymap` yourself:
Just removing the `vim.api.nvim_set_keymap` should solve the issue.

**Comment by pidgeon777** [comment]
I confirm that fixed the issue. Thank you!
