### ISSUE TITLE
conflict with ku1ik/vim-pasta

### ISSUE THREAD

**Issue by chapeupreto** [tzachar/highlight-undo.nvim#35]
I started using `highlight-undo.nvim` and just noticed that it conflicts with `ku1ik/vim-pasta` plugin.

When I use the `p` (or `P` keys) the highlighting doesn't work as expected.

When I do `:verbose nmap p`  I can see the following results:

```
n  p            @<Plug>AfterPasta
        Last set from ~/.local/share/nvim/plugged/vim-pasta/plugin/pasta.vim line 55
n  p           * <Lua 216: ~/.local/share/nvim/plugged/highlight-undo.nvim/lua/highlight-undo.lua:143>
        Last set from Lua (run Nvim with -V1 for more details) line 699
```

If I remove `ku1ik/vim-pasta` everything works fine!

I am using `junegunn/vim-plug` as my plugin manager.

Does anyone know how to get both of the plugins working? Or is there any alternative for `vim-pasta` that is more `Neovim` tailored?

**Comment by xzbdmw** [comment]
you don’t need to use vim-paste, I hate most vim plugins remapping keybinding by default.
https://github.com/xzbdmw/nvimconfig/blob/c45e82f7fa7965323e73320c3daa1bcb09195bd8/lua/plugins/yanky.lua#L62

**Comment by tzachar** [comment]
I believe this is related to the order the plugins are loaded. Try loading `highlight-undo` last.

**Comment by chapeupreto** [comment]
> I believe this is related to the order the plugins are loaded. Try loading `highlight-undo` last.

Thanks for your reply. How do I do that considering I use `vim-plug` as my plugin manager?

**Comment by tzachar** [comment]
I assume the order you call vim-plug with the plugins matter.
