### ISSUE TITLE
If the keymaps option is not passed, the plugin fail to load.

### ISSUE THREAD

**Issue by Zeioth** [tzachar/highlight-undo.nvim#6]
It would be a good idea to implements default values to avoid this.

**Comment by mcauley-penney** [comment]
Default keymaps were implemented in e732a9c, before this issue was made. This error should be solved as of #4. If you've updated your plugin in the past hour, please add details such as error messages. If you have not updated, please do so and reply if the problem persists.

**Comment by Zeioth** [comment]
Correct it's been fixed. Closing ❤️
