### ISSUE TITLE
Question: do I need to configure `HighlightUndo`? Nothing is highlighted

### ISSUE THREAD

**Issue by gilbh** [tzachar/highlight-undo.nvim#8]
Here's my lazy setup:
```
    {
      'tzachar/highlight-undo.nvim',
      config = function()
        require('highlight-undo').setup({
          hlgroup = 'HighlightUndo',
          duration = 300,
          keymaps = {
            {'n', 'u', 'undo', {}},
            {'n', '<C-r>', 'redo', {}},
          }
        })
      end
    }
```

Nothing is showing with undo/redo. Do I need to configure `HighlightUndo` and if yes, how?

Thanks!

sys info:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎13/‎2021
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by tzachar** [comment]
`HighlightUndo` is defined by the plugin.
you can check:
`:highlight HighlightUndo`

should return `HighlightUndo  xxx cterm= gui= guifg=#dcd7ba guibg=#2d4f67`

Other than that, your config looks fine. Are you on the latest version of the plugin?

**Comment by gilbh** [comment]
Thanks.

Indeed, this is exactly what I get:
![image](https://github.com/tzachar/highlight-undo.nvim/assets/39532610/faa29a83-a0a7-40e1-88bb-f4cb63008c4b)

Still, nothing is highlighted when I undo/redo ... 

Here's the version info from Lazy:
![image](https://github.com/tzachar/highlight-undo.nvim/assets/39532610/04e5b57d-7aa6-4c74-93d4-f4f60488ccef)


Any ideas?

**Comment by gilbh** [comment]
Right, finally caught the culprit -- another plugin that mapped `u` and `<c-r>` (`mini.bracketed`). Solution was very easy: I just moved the setup() of `highlight-undo` *after* that of `mini.bracketed`. Thanks for this!

**Comment by tzachar** [comment]
cool.
glad you could find the problem.

**Comment by JamesTeague** [comment]
@gilbh Excellent find. Just out of curiosity to help me get better at this stuff. Do you remember how you found this?

**Comment by tzachar** [comment]
which-keys can sometimes help you there.
