### ISSUE TITLE
Doesn't work when switching colorscheme

### ISSUE THREAD

**Issue by alexxGmZ** [tzachar/highlight-undo.nvim#9]
when i type ```:colorscheme <name>``` the undo highlight disappear

**Comment by tzachar** [comment]
This is because calling `:colorscheme <name>` clears all highlighting groups.
You need to define the `HighlightUndo` group yourself after calling it.
If you cannot set up your configuration to that effect, you can try hooking to the `ColorScheme` autocommand.
